### ISSUE TITLE
TodoOffline SyncHandler.cs - Issue on Line 38

### ISSUE THREAD

**Issue by mchipeta** [Azure/mobile-services-samples#43]
Line 38 should be changed from

JObject result = await operation.ExecuteAsync();

to

JObject result = await tryOperation.Invoke();

https://github.com/Azure/mobile-services-samples/blob/master/TodoOffline/WindowsUniversal/TodoOffline/TodoOffline.Shared/SyncHandler.cs#L38

**Comment by lindydonna** [comment]
Fixed in e66e724
