### ISSUE TITLE
Windows 10 Offline ToDo ??

### ISSUE THREAD

**Issue by djaus2** [Azure/mobile-services-samples#62]
I have a Windows 10 Universal Platform App that gets and puts info to a Mobile Service table.
I want to change this to work off line as the data will only be modified when the app is first used, normally.  So I'd like to use a local SQLite database that can push and pull with the Mobile Service.

Is there and version of the OffLine ToDo app  for C# Windows 10 Universal?
I've have tried working through the changes as per the Windows 8.1 version but run into all sorts of version and API issues.

Thanks in advance.

**Comment by adrianhall** [comment]
You can check out my QuickStart that is written for Azure Mobile Apps and UWP here: https://github.com/adrianhall/quickstarts

Look in the Quickstart.UWP folder.
