### ISSUE TITLE
{"message":"Authorization has been denied for this request."}

### ISSUE THREAD

**Issue by manikandansai** [Azure/mobile-services-samples#68]
I Have not enabled authorization for this mobile service api. Worked locally . after publishing throwing authorization error

**Comment by lindydonna** [comment]
We use GitHub issues for bugs only. For app questions, please post on https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=azuremobile. Please mention whether you are using Mobile Services or Mobile Apps, whether you are using Node.JS or .NET, and the exact error that you are getting after publishing.
